require "spec"
require "../src/crcqrs"
require "../src/command"
require "../src/aggregate"
require "../src/macros"
require "../src/event"
require "../src/stores/memory"
require "../src/stores/evento"
